version: '3.1'
services:
  routes_scrapes_db:
    image: mysql:5.7
    command: --default-authentication-plugin=mysql_native_password
    ports:
      - 4000:3306
    environment:
      - MYSQL_ROOT_PASSWORD=cnsC61PPlRxOdh0-rt-secret
    volumes:
      - mysql-data:/var/lib/mysql
  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
  node-app:
    image: mrobot19/routes-scraper:1.0.1
    ports:
      - 3000:3000
    environment:
      - DB_HOST=routes_scrapes
      - DB_NAME=routes_scrapes
      - DB_USER=root
      - DB_PASS=cnsC61PPlRxOdh0-rt-secret
volumes:
  mysql-data: